### ISSUE TITLE
Expose 'func (Time) Add' function in template engine

### ISSUE THREAD

**Issue by ayashjorden** [bosun-monitor/bosun#1014]
Hi,
In our use-case, we're generating Kibana URLs that include timestamps for dashboard time-window display.
Currently, I can put either fixed ```<time>-ago``` notation (4h-ago) or absolute time (from t1 to t2).

A relevant time-frame can be injected to the generated URL by taking the alert timestamp and subtracting  a duration using ```time.Add(<negative_duration>)```. the resulting Dashboard URL will always display a time-window like 1 hour before the alert until 'now'.

Thanks,
Yarden

**Comment by kylebrandt** [comment]
The time add function is exposed based on the alert property. What we would need to expose is actually time duration. You can use this ugliness as a workaround:

`{{($.Last.Time.Add -1.8e12).Format "2006-01-02T15:04:05Z" }}'`

Here is a complete URL for reference:

`<a href="http://kibana/#/discover?_g=(time:(from:'{{($.Last.Time.Add -1.8e12).Format "2006-01-02T15:04:05Z" }}',mode:absolute,to:'{{($.Last.Time).Format "2006-01-02T15:04:05Z" }}'))&_a=(columns:!(_source),index:%5Bhaproxy-%5DYYYY.MM.DD,interval:auto,query:(query_string:(query:'ForwardFor:*{{ $ip.ip }}*%20OR%20ClientIp:{{ $ip.ip }}')))">{{ $ip.ip }}</a></td>`

The bad thing is using the numerical constant. But this will likely let you get the job done. Note that my example is `$.Last.Time` because I'm inside a nested block and need to access the parent scope. You can probably just do `.Last.Time`

**Comment by ayashjorden** [comment]
I forgot about this ticket, what I ended up doing (which (IMHO) is better) is:
```
$kibana_parameters = ?_g=(time:(from:'AAAA:00:00.000Z',mode:absolute,to:now))
```
And in the template rendering:
```
<a href='{{replace .Alert.Vars.url "AAAA" (.Last.Time.Format "2006-01-02T15") 1}}'>View Dashboard</a>
```
The ```.Alert.Vars.url``` is a concatenation of several parts of our full Kibana URL.
This truncates the minutes from the hour and lets the user view a (slightly) bigger picture.

Thanks,
Yarden
