### ISSUE TITLE
Documenting expression function arguments

### ISSUE THREAD

**Issue by mjibson** [bosun-monitor/bosun#1026]
The docs for our expression arguments are totally unclear, and only usable with examples. The problems are:

1. The difference between number and scalar is confusing. It should be obvious (somehow) that scalars are just normal numbers, and a "number" is the result of an expression that is a series. The tagged vs untagged thing here is hard to explain.
2. Arguments are sometimes named and sometimes typed. That is, sometimes we describe the type of the argument, and sometimes we put a human-readable name as the argument. We need to do both.
3. Return types are also poorly documented.

We need to come up with a standard format to describe these. Here's a proposal:

`## func_name(var_name var_type[, name2 type2]) return_type`

Example:

```
## forecastlr(s series, y_val scalar) number

Returns the number of seconds a linear regression predicts s will take to reach y_val.
```

**Comment by kylebrandt** [comment]
All types should href link to the type def in document

**Comment by kylebrandt** [comment]
Matt and I agreed that changing these to seriesSet, numberSet, and scalar will help make things clearer. Thanks to Greg for highlighting and clarifying this point of confusion!

**Comment by gbrayut** [comment]
Some other examples to keep in mind when trying to figure out the new format:

**lookup(table, key)** Kyle and I were not even sure what the return type was for this function

**sort(number, asc_desc)** A better syntax for restricted arguments would be nice, like <"asc" | "desc">

**filter(series, number)** If I remember correctly this has a different return type than most other functions. When using in an expression you may not notice, but if you use these results in a template it may behave differently than other functions.

Speaking of which, whatever format we use to document expression functions we should also plan on using to document template functions. These have a different invocation due to how go templates work, but are much more particular about input types ( an int literal like 1 does not work where a double is required). Not saying it needs to exactly match how we document expressions, but whatever we do now should eventually line up with what we use to document template functions.

Example of a template/functions we may want to document using a similar same syntax:

```
{{$sources := (.EvalAll .Alert.Vars.source).DescByValue}}
{{$top_source := index $sources 0}}
{{$source_display_at := .Eval .Alert.Vars.source_display_at}}
...
{{ if not .IsEmail }}
            {{if gt (.Eval .Alert.Vars.sources_display_count) 1.0}}
                Sources: {{range $r := $sources}}
                    {{ if gt $r.Value $source_display_at }}
                        https://{{$.LookupAll "exception_source" "hostname" $r.Group}} = {{$r.Value | printf "%.f"}}
                    {{end}}
                {{end}}
            {{end}}
```
