### ISSUE TITLE
lookup inside an alert not working

### ISSUE THREAD

**Issue by ayashjorden** [bosun-monitor/bosun#1035]
Hi,
The scenario is as follows:
1. in Rule Editor page, add lookup object and alert using the lookup.
2. test the newly added alert.

result: empty result in 'Result' view
![image](https://cloud.githubusercontent.com/assets/4204371/7985795/17d62f74-0adc-11e5-9b01-e809367b736d.png)

**Comment by gbrayut** [comment]
Try using a hard coded LookupAll to see if it is the tag matching that is failing:

warn = $srv_doc_count < LookupAll(“min_doc_per_host”, “warn_min”, “host=mail-work-test”)

**Comment by kylebrandt** [comment]
Lookupall is only a template func

**Comment by gbrayut** [comment]
Differences between expression functions and template functions makes me a sad panda.

**Comment by yinchuan** [comment]
Seems like `lookup()` only works for OpenTSDB.   
env: CentOS 6.6 x64, bosun-linux-amd64 v0.3.0
In my test, using default docker image, 
```
tsdbHost = localhost:4242
stateFile = /data/bosun.state

template test {
	subject = test subject
	body = test body
}

lookup test {
    entry host=* {
        crit = 100
        warn = 60
    }
}

alert test {
	template = test
	crit = avg(q("avg:rate:os.cpu{host=3d862cebca3e}", "5m", "")) > lookup("test", "crit")
}
```
This works like a charm, `lookup()` gets right value.

But, chage to graphite backend, use config as below:
```
graphiteHost = http://192.168.2.53/render/
stateFile = /data/bosun.state

template test {
	subject = test subject
	body = test body
}

lookup test {
    entry host=* {
        crit = 100
        warn = 60
    }
}

alert test {
	template = test
    crit = avg(graphite("bj2-monitor.metrics", "1h", "", "host.metrics")) > lookup("test", "crit")
}
```

Get same result with @ayashjorden , with no Errors, no any output.

**Comment by yinchuan** [comment]
by the way, use LookupAll in template can get write value.

**Comment by yinchuan** [comment]
@ayashjorden Hello, any idea about this?

**Comment by ayashjorden** [comment]
Hi @yinchuan, 
It will take me few more days to get back to this, sorry that I don't have more helpful answer.

Yarden

**Comment by yinchuan** [comment]
@mjibson Hello, any idea about this?

**Comment by cheribral** [comment]
I ran into this as well.  Working with the forecasting example for disk space, I changed it to use some static numbers, and put in an extra variable to see what was happening.
```
$warn_percent = $percent_free <  80
$crit_percent = $percent_free <  90
$blah = 0 < lookup("disk_space", "crit_percent_free")
```
I set the notification to print, and put all three in the subject line.  It is printing $blah as `0 < lookup("disk_space", "crit_percent_free")` literally as if it were a string rather than evaluating it.  All the other variables are printed correctly as the result of the expression.

**Comment by kylebrandt** [comment]
I'm think that this is because we are using search, so unless you are on OpenTSDB *and* you are sending datapoint to /index (or relayig through bosun) search would have no results:

https://github.com/bosun-monitor/bosun/blob/97df011b2451b1c814679eec1ede1b700901c575/cmd/bosun/conf/lookup.go#L28

**Comment by kylebrandt** [comment]
That func I pointed at doesn't use search data, this one does though: https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/conf/conf.go#L1209

**Comment by ayashjorden** [comment]
@kylebrandt 
I understand that Lookups works only when using OpenTSDB?

I though I can use the Lookup structure to write generic configuration. meaning using a lookup in alerts.

**Comment by captncraig** [comment]
Correct, the lookup function as is relies on search to find tag keys and values. The problem is `lookup` is really a standalone expression. It is given no context of what tags exist or that to do. I can think of two real solutions to this:

1. Create a `lookupC()` function that accepts an expression to use as the context for it's lookup.

I think this would lead to a lot of things like 

```
$foo = q(....)
crit = $foo > lookupC($foo, "lookup_name", "field")
```

which feels a littel cumbersome, but would be explicit.

2. Attempt to infer the context from the expression. If we assume/enforce that a lookup is only valid inside a binary operation, we can get the tags from the non-lookup side and pass them into the lookup as context.

Example:

```
$foo = q(...)
crit = $foo > lookup("lookup_name","field")
```

We can evaluate the query, pull out the unique tag sets and pass that as the context to the lookup. The lookup can then create one result per source tagset and the results will union perfectly. This should also be nice as it won't need to query anything additional outside of the current expression. That logic would all need to be somehow done in `walkBinary` though, so lookups may not be valid elsewhere.

**Comment by kylebrandt** [comment]
I think this is correct. I can't think of lookups having any meaning outside of this case, except maybe if you wanted to pass the value of a lookup to a function. I don't think we do that anywhere currently.

**Comment by kylebrandt** [comment]
Digging into this, I found out there is already a function that works around this that wasn't documented:

```
		"lookupSeries": {
			Args:   []models.FuncType{models.TypeSeriesSet, models.TypeString, models.TypeString},
			Return: models.TypeNumberSet,
			Tags:   lookupSeriesTags,
			F:      lookupSeries,
		},
```

So all you have to do is pass your series into the function:

```
lookup test {
    entry host=ny-bosun01 {
        value = 1
    }
    entry host=* {
        value = 2
    }
}

template test {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `<p>Name: {{.Alert.Name}}
	<p>Tags:
	<table>
		{{range $k, $v := .Group}}
			<tr><td>{{$k}}</td><td>{{$v}}</td></tr>
		{{end}}
	</table>`
}

alert test {
	template = test
	$q = q("avg:rate:os.cpu{host=*bosun*}", "5m", "")
	crit = avg($q) > lookupSeries($q, "test", "value")
}
```

![image](https://cloud.githubusercontent.com/assets/1692624/13588379/5602e2a6-e49d-11e5-8337-96a8f3c4af7b.png)

**Comment by angadsingh** [comment]
would be great to have this added to the documentation. took us a while to reach this thread.
