### ISSUE TITLE
Better auto complete suggestions and scrollbars on graph pages

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1036]
I think our auto complete suggestions could be improved. Searching for win.mem should rank ^win.mem higher than *win.mem. RIght now I have to type most of the metric name out before I get an auto complete suggestion that is close to what I want.

Also, the list should support scrolling.

![image](https://cloud.githubusercontent.com/assets/304401/7989383/60850c58-0aa6-11e5-97db-9a764b68dc77.png)

That is missing 4 metrics, which could be displayed with scrollbars or better matching

![image](https://cloud.githubusercontent.com/assets/304401/7989420/95955132-0aa6-11e5-831d-393ff02052f3.png)

**Comment by bretcope** [comment]
I would add to this that autocomplete would likely be a lot more pleasant if it worked like code intellisense. We use the dots in metric names to describe a hierarchy, the same way the dot (access operator) is used in code to navigate a hierarchy. If `win` were an object, and I typed `win.` into an IDE, it would only show me `mem` once, without any of its subproperties. This allows you to navigate where you want to without nearly as much noise. It also helps with discovery because, instead of seeing the same thing dozens of time, I see all of the unique items in the next level of the hierarchy, and I can follow the paths which interest me, while easily ignoring the ones which don't.

I realize what I'm suggesting is likely more difficult to implement than whay Greg is suggesting, but I thought I would throw it out as a direction we might want to consider.

**Comment by mjibson** [comment]
Bret, I'm going to close this issue to fix Greg's comment. I've opened another with your suggestion.
