### ISSUE TITLE
Track if a process is running or not

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1079]
Add some metric to help track if a process is running or not. I guess a simple way to do it is to send the number of processes currently matching each [[Process]] entry

**Comment by gbrayut** [comment]
I agree that we need this, but keep in mind that right now at Stack Exchange we have a single toml file that defines all the monitored processes. We wouldn't want our lbs saying that redis isn't running, since redis has never been run on that system. We may have to somehow filter to processes that are registered in systemd/init or that have been seen previously, or we may just need to bite the bullet and customize the toml file for each host (althought this goes against the "automatically start monitoring" goal a bit)

**Comment by dimamedvedev** [comment]
I can try to do that "filter to processes that are registered in systemd/init" part in #1161 . Although with sysv initd getting registered/enabled status is not an easy feat, easy with systemd/runit.

**Comment by gbrayut** [comment]
Reopening. Was closed via 1316 but we also plan on adding service tracking for SystemD and other init systems.

**Comment by kylebrandt** [comment]
I believe we did this.
