### ISSUE TITLE
/api/alerts route does not filter silenced alerts when a filter spec is applied

### ISSUE THREAD

**Issue by PeterGrace** [bosun-monitor/bosun#1088]
To reproduce, load `http://bosun.ds.stackexchange.com/api/alerts?filter=nyhq` -- you will see that Groups is properly filtered, but Silenced returns all entries.

**Comment by mjibson** [comment]
The documentation on bosun.org doesn't say it's supposed to filter silenced alerts. Is this something it used to do and doesn't anymore? Does it work differently if there's no filter applied?

Also, this route changed in the last few weeks and now returns the silenced status with each alert instead of a separate object.

**Comment by kylebrandt** [comment]
The idea behind silence is that it prevents notifications, but you still have a way to see if the alert triggered. This is useful during maintenance. One can watch the dashboard without generating what would be alert noise to anyone not involved in the maintenance. Therefore I think indicating silence is acceptable as anyone consuming the API can process the JSON accordingly.
