### ISSUE TITLE
Paralellize alerts

### ISSUE THREAD

**Issue by captncraig** [bosun-monitor/bosun#1228]
Create a goroutine per alert that runs the alert independently.

If one alert takes a long time, it will not affect other alerts.

The gorutine will maintain the current state for the alert, and will manage all mutations to that state (template rendering, status updating). It can then merge that state into the "global" schedule state via thread-safe mechanism. Global state will be essentially read-only.

Dependencies will be slightly affected. Alerts will still run the expressions from depended-upon alerts in real-time, but if the depended-upon alert is unknown or unevaluated, we will rely on the last known state in the global state.

**Comment by captncraig** [comment]
Added with #1231

**Comment by Dieterbe** [comment]
> Dependencies will be slightly affected. Alerts will still run the expressions from depended-upon alerts in real-time, but if the depended-upon alert is unknown or unevaluated, we will rely on the last known state in the global state.

does this change dependency semantics from "use current dependency status" (as it was before), to "use either the current dependency status or the dependency status of the previous run" ?
if so, i wonder if there's a nice way to solve this, perhaps still orchestrating an order in between otherwise parrallel running alerts.
