### ISSUE TITLE
KairosDB backend

### ISSUE THREAD

**Issue by lcoulet** [bosun-monitor/bosun#1235]
Hi,
I'd like KairosDB to be added as backend to Bosun.

I am able to help on this since I know KairosDB almost perfectly, but I cannot find any documentation about Bosun internals and how I may be able to add a new backend easily. 

It looks to me at the first glance that the backends are all pretty much hardcoded all pover the place and adding an additional one would require a large fork...I mean updating at least a dozen of source files. Am I correct?
Otherwise, is there any interface in can implement and register in the config to add another backend?

**Comment by kylebrandt** [comment]
Updating a dozen source files is what it will take. We will happily merge in KairosDB support once it is ready.

Since you know KairosDB and what I understand to be its similarity to opentsdb, I don't think you will have much trouble getting this started at all assuming some Go experience. This unmerged branch comparison is for infuxdb (influx has some difficulties since due to its behaviors, and we don't have a mainter, so it is not merged). That being said in general the code should be a good model:

https://github.com/bosun-monitor/bosun/compare/influxdb-query

Hop in slack chat, inviter on the http://bosun.org , for more questions, or just update this issue. I'm excited about getting a Kairos backend!

**Comment by digrich** [comment]
+1

**Comment by Freeaqingme** [comment]
I'm also interested in Kairos integration. The referred branch does seem to no more exist. Has there been any progress made in this respect, or is there perhaps some set of other pointers I could use to pick up  on this feature? (time is a limiting constraint, so don't get your hope up, just yet ;))

**Comment by xiaoxiaoSDNMAX** [comment]
good idea

**Comment by seesiva** [comment]
Is there an update on using Kairosdb/Influxdb with bosun

**Comment by captncraig** [comment]
Influxdb works. Scollector can send data to it if you activate the opentsdb listener on the influx server and it will work. Influx query support has been availible for some time now, and it works well.

**Comment by farzadpanahi** [comment]
Any update on kairosdb support?

**Comment by kylebrandt** [comment]
PR for KairosDB would be welcome, but nobody on the core bosun team plans to implement it any time soon. So closing this. The documentation will be updated if someone adds it as a backend at some point.

**Comment by jf** [comment]
hey @kylebrandt , just updating this for Aug 2017: how should one start possibly looking into a PR for today? https://github.com/bosun-monitor/bosun/compare/influxdb-query is no longer a valid url

**Comment by kylebrandt** [comment]
This current WIP might help you https://github.com/bosun-monitor/bosun/pull/2143/files
