### ISSUE TITLE
Influx query language improvements

### ISSUE THREAD

**Issue by giganteous** [bosun-monitor/bosun#1298]
I'm trying to get better support into bosun, and for this I'm trying out different examples from the documentation page and adapting them to the influx() function.

Given the os.diskspace alert, we have this opentsdb query:
```
q("avg:6h-avg:os.disk.fs.percent_free{host=netlog*,disk=*}", "7d", "")
```

I think I have a similar query to get the data from influxdb, correct me if i'm wrong:
```
select mean(value) from "os.disk.fs.percent_free" WHERE host =~ /netlog.*/ and time > now() - 7d group by time(6h), host, disk
```

The current problem:

1) influx() wants the time outside the query, or it will complain with
```
  influx($db, '''select mean(value) from series WHERE host =~ /netlog.*/ group by time(6h), host, disk''', "7d", "")
```
  => **aggregate functions with GROUP BY time require a WHERE time clause**

Adding it, will complain too:
```
  influx($db, '''select mean(value) from series WHERE time < now() - 7d host =~ /netlog.*/ group by time(6h), host, disk''', "7d", "")
```
  => **influx query must not contain time in WHERE**

Is there a dependency somewhere in the code on this argument style? I.e: is it possible to ditch the start/end arguments for influx()?

**Comment by giganteous** [comment]
I've pushed some changes to [my bosun repo in an experimental branch](https://github.com/giganteous/bosun/tree/less-arguments-for-influx). This gives me at least a function to simulate these same alerts with.

**Comment by giganteous** [comment]
Ah. This is the influxTag() function [at line 27 of influx.go](https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/expr/influx.go#L27). The influx querylanguage must have some info on how to retrieve those. Perhaps @nathanielc can assist me?

**Comment by nathanielc** [comment]
The two errors you are getting are an artifact of the way the query is constructed.

The first `aggregate functions with GROUP BY time require a WHERE time clause` is just complaining that you can't groupby time if you haven't also added  a where clause on time. Pretty self explanatory.

The second error `influx query must not contain time in WHERE`is coming from the bosun specific code saying that the `influx` method wants to add the time clause itself to the query and if there is already one its considered invalid.

The combination of these tow errors creates a cyclic dependency that means you can''t use group by time in your influx queries. 

There is a simple solution though. Since bosun is constructing a query with its own time clause, bosun also needs to handle adding the groupby time clause as well. This way the raw query passed to bosun will not have either a time where clause or a groupby time but will be added based on the other parameters passed to the method.

I will not have time to look at this for a while but here is some example code I used before to do this exact same thing:

First: Add another parameter to the bosun method `influx`  called `group_by_time_interval` or something.

Second: If that parameter is not empty and is a valid duration string then add a groupby clause to the constructed query like so:

Place this code about here https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/expr/influx.go#L152

```go
groupByInterval, err = time.ParseDuration(groupByIntervalStr)
if groupByInterval > 0 {
		s.Dimensions = append(s.Dimensions,
			&influxql.Dimension{
				Expr: &influxql.Call{
					Name: "time",
					Args: []influxql.Expr{
						&influxql.DurationLiteral{groupByInterval},
					},
				},
			},
		)
	}
```

Using your example the influx method would look like this
```
influx($db, '''select mean(value) from series WHERE host =~ /netlog.*/ group by host, disk''', "7d", "", "6h")
```
Hopefully that is enough to get you started.

**Comment by giganteous** [comment]
Okay, here is a rough draft for the documentation on #1304, with remaining notes., I'm interested in your views wrt the nil values that Influxdb can return.

## InfluxDB Query Functions                                                       

### influx(db string, query string, startDuration string, endDuration, groupByInterval string) seriesSet

Queries InfluxDB.

All tags returned by InfluxDB will be included in the results.

* `db` is the database name in InfluxDB
* `query` is an InfluxDB select statement
    NB: WHERE clauses for `time` are inserted automatically, and it is thus an error to specify `time` conditions in query.
* `startDuration` and `endDuration` set the time window from now - see the OpenTSDB q() function for more details
    They will be merged into the existing WHERE clause in the `query`.
* `groupByInterval` is the `time.Duration` window which will be passed as an argument to a GROUP BY time() clause if given. This groups values in the given time buckets. This groups (or in OpenTSDB lingo "downsamples") the results to this timeframe. [Full documentation on Group by](https://influxdb.com/docs/v0.9/query_language/data_exploration.html#group-by).

### Notes:

  * By default, queries will be given a suffix of `fill(none)` to filter out any nil rows.
