### ISSUE TITLE
Can I access bosun through any reverse proxy server?

### ISSUE THREAD

**Issue by digrich** [bosun-monitor/bosun#1398]
I am trying to access bosun through a reverse proxy server and noticed that all resources and api calls are getting failed because they are mapped directly to root. 

I am trying to include bosun in our corporate management portal and trying to call through a reverse proxy server.

mapping :
http://example.com/bosun -> http://bosun:8070/

Is there anyway I can achieve this?

**Comment by timurb** [comment]
I'd love to have this too.

**Comment by timurb** [comment]
Looks to be the same as: https://github.com/bosun-monitor/bosun/issues/403

This is essentially only about letting user to specify a config parameter which will be use inside HTML hrefs (like having `/bosun/static/css/bootstrap.min.css` instead of `/static/css/bootstrap.min.css` inside HTML code). This is a non-trivial task to do outside of the application.

All other parts (like modifying location headers and mapping `/bosun/api/...` to `/api/...` in HTTP requests) are easily done by web-proxies and you don't need to handle this inside Bosun.

**Comment by captncraig** [comment]
I'm trying to make this work. Using nginx in this config:

```
  server {
        listen       9999;
        server_name  localhost;

        location /bosun/ {
            proxy_pass http://127.0.0.1:8080/;
      }
```
I have no idea what I am really doing, but that seems to do the general right thing. There are a lot of issues with front end resources using absolute links vs relative links. Once I get that sorted, I can start to debug server-side generated links.

**Comment by timurb** [comment]
@captncraig probably it's not the best place to discuss nginx configuration but I'll walk you through it so that everyone understands what's missing here.

The config you've posted does the following:
* nginx sends all requests under http://$HOSTNAME/bosun/ to service running on port 8080 on localhost with `/bosun/` part stripped. I assume that you are running Bosun on this port but not on default 8070. (see http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass for more info)
* when this proxied server returns `http://localhost:8080/` in `Location` and `Refresh` headers of its response it is rewritten to `http://$HOSTNAME/bosun/` and returned to the browser. I don't quite understand what that means but this probably doesn't relate to how Bosun works now. (see http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_redirect for more info)

Please note, this processes only request/response headers and has nothing to do with actual HTML body. AFAIK you can't do this easily without some hardcore hacking (please let me know if I'm wrong).

Now here is what happens when a browser retrieves Bosun's front page:
* browser sends a request to http://$HOSTNAME/bosun/ and a HTML file is successfully received as a response
* in that file there are some links like `/items` or `/partials` or CSS/JS files which are relative not to "current path" but to "server name", see the next step for what this means (actually I think all of the links are like such)
* browser sends request to `http://$HOSTNAME/items` while to really receive that link it should send request to `http://$HOSTNAME/bosun/items`. That is the browser sends request to incorrect locations due to incorrect HTML for this case returned by Bosun.

I see the following ways to solve this:
* have Bosun return links inside HTML relative to current location but not to root (that is `items` instead of `/items`). Don't really know if this is going to work.
* have Bosun return full URL as those links (that is `http://$HOSTNAME/bosun/items` instead of `/items`). Usually applications have something like "baseurl" parameter in their config which is prepended to all links. Probably it also can be extracted from HTTP headers.
* do parsing of HTML on nginx-side and replace all links like `/items` to correct ones. Probably you still can't change that in JS and I don't think anyone is going to do this due to complexity
* change all such locations in Bosun source and recompile a package for yourself. Don't know how complex it is without getting too much into Go hacking 
* create 2 nginx rules (actually much more) to proxy Bosun first page at `/bosun/` but make nginx proxy all bosun's subdirs at their own locations. That is `/bosun/` will be proxied to `http://localhost:8080/` and `/items` will be proxied to `http://localhost:8080/items`. This introduces complexities in configuring nginx (you need to maintain a dozen locations instead of a single one) and can break setup with Bosun upgrades and also may clash with other software running on the same host.

The most handy way for the community would be having a parameter in Bosun config to prepend it to all links, as describe in the second point.

**Comment by digrich** [comment]
I also raised the same request on some other thread. This would be a good
support to have. I need to incorporate bosun UI in our main portal through
reverse proxy but couldn't do successfully. It would be really good if we
can define a base url in the configuration file for all static resources.

**Comment by timurb** [comment]
@digrich could you please post a link here for reference?

**Comment by digrich** [comment]
@timurb sorry for confusion, it's a current thread only which I started.

**Comment by awesensepaul** [comment]
I agree this would be extremely useful. In #403 it was suggested to configure this in the reverse proxy config. This may work for the web frontend, but it doesn't help for e-mails with links sent to 127.0.0.1:8070. Currently I use golang strings.replace to re-write this in custom templates to the correct URL. This obviously doesn't work for e-mails with non-customizable templates such as acknowledgement notification e-mails.

I think a configuration option is the best approach; it is what I expected based on the other monitoring software we are hosting, and if bosun sends links within e-mails, there is no reverse proxy setting that can possibly address that.

**Comment by timurb** [comment]
@awesensepaul for using in e-mails there's already a `hostname` parameter.
Could it be reused in HTML/JS pages as well?

**Comment by awesensepaul** [comment]
Alright, that `hostname` parameter does help with the e-mails, thanks. I would prefer if there was also a way to set the scheme to https (or just default to https, really); but my reverse proxy is already configured to re-direct anything from HTTP -> HTTPS.

There is still no way within the bosun config to append a path to the url or use a URL prefix for all URLs generated (e.g. `/mybosun/` and/or `https://foo.bar.com/mybosun/`). I would prefer the URL prefix approach since it encompasses `scheme + hostname + port + path` in a single config setting.

The most minimal implementation I can think of would only need to *generate* the URLs with this prefix; it is straightforward to configure a reverse proxy to re-write these from `https://foo.bar.com/bosun/incident` to http://127.0.0.1:8070/incident` (e.g. the routing for `/incident` and other endpoints can remain the same).

**Comment by majj** [comment]
+1

grafana for reference:

[http://serverfault.com/questions/684709/how-to-proxy-grafana-with-nginx](http://serverfault.com/questions/684709/how-to-proxy-grafana-with-nginx)

**Comment by fradaloisio** [comment]
I've made some modification/hack to let it work with the URL http://myHost.com/alerting/
- apache configuration [here](https://gist.github.com/fradaloisio/6d430b62fcf54fe0d5cc28c10f0e8d89)
- bosun.js [here](https://gist.github.com/fradaloisio/32d21004d347383464efbe13c4656866)

**Comment by devblok** [comment]
This is still open. Is this implemented at all in the newer versions, or is it still the same?
