### ISSUE TITLE
FreeBSD release

### ISSUE THREAD

**Issue by benrubson** [bosun-monitor/bosun#1399]
Hello,

Could it be possible to make a FreeBSD release of scollector please ?
Does not seem to exist yet according to the download page :
http://bosun.org/scollector/

Goal is to run scollector from FreeBSD servers to send data to Runabove :
https://www.runabove.com/iot-paas-timeseries.xml

Thank you very much !

**Comment by jevonearth** [comment]
+1

**Comment by captncraig** [comment]
The issue here is not feasibility. It would be a simple addition to our build scripts to generate the executable.  The problem is that it wouldn't collect very much data there.

Most of our collectors are in `foo_linux.go` or `foo_windows.go` files which means they would not be included in a freebsd build. Many of the linux ones may or may not work on freebsd (I don't really know anything about freedsb tbh). Even if they would run, the files would need to be renamed, and appropriate build tags added. Others that are important enough may need to be rewritten to do things the freebsd way.

I don't really want to release a freebsd version that doesn't do anything. We did that with solaris once and it ended up getting reversed. If you are willing to work on getting it working it would be a welcome addition. Without any freebsd boxes here at stack, it is hard for us to support it though.

**Comment by jevonearth** [comment]
So you use build flags to build the appropriate support for the target? Or do you determine the os type at run time, and use the appropriate [windows|linux|darwin] collector implementation via some interface?

I can just go read the code more, but you may be able to cast more light on that matter :)

**Comment by kylebrandt** [comment]
It is a go thing, when the filename has something like `_windows.go`it only builds that file on Go. So we have some standard stuff we collect on each platform, such as cpu, memory, disk etc. The only things that would currently build on freebsd would have no extension like that, or a _unix extension.

So before bothering to make a build, there should probably be at least barebones collectors that get OS vitals. Our pattern is to use the os. namespace for things that are shared across operating systems. We make sure that they have the same semantics as far as tags, and counter vs gauge, maximum value etc.

So in order to make a build worthwhile, we would want:
os.cpu
os.net.bytes, os.net.virtual.bytes, etc
os.mem...
os.disk...

You can also have more detailed metrics that related to those under freebsd (or maybe bsd, if they are all the same in these regards?). Looking at our docker instance should give you an idea.

We would also want someone with interested in supporting these contributions over time. Otherwise we are having a build of scollector that makes it look bad, essentially.

**Comment by captncraig** [comment]
Freel free to join us in slack if you want to talk in more detail. http://bosun.org/slackInvite

**Comment by tdinucci** [comment]
Very old issue and this is not something that we could practically support
