### ISSUE TITLE
Allow "Metrics and Hosts" tab to be populated by a database query

### ISSUE THREAD

**Issue by cheribral** [bosun-monitor/bosun#1433]
From what I understand, which may be wrong, this page is populated by proxying the data streams through bosun so it can index the metadata or by feeding it in manually through the API.

Since databases like influxdb have all this information already, it would be nice not to have to maintain this separately.  Would it be possible to populate this page based on a query, much like the template variables are handled in grafana?

**Comment by gbrayut** [comment]
You are correct, the items tab currently requires that you send data either directly to bosun (which proxies it to the OpenTSDB host) or use something like cmd/tsdbrelay to forward a copy of the metrics to the http://bosun.org/api#apiindex route.

Since there can be multiple backend we probably need to reconsider how metric information is collected, but this is not likely to happen anytime soon unless someone else wants to work on it. The items, host, and graph tabs for the time being will only work with OpenTSDB and work best when bosun can index the incoming data.
