### ISSUE TITLE
Elasticsearch 2.x Support

### ISSUE THREAD

**Issue by awesensepaul** [bosun-monitor/bosun#1444]
Elasticsearch 2.0.0 was officially released already. The gopkg `elastic.v3` is also officially released, which includes support for any new features.

Current Bosun in `master` cannot connect to elasticsearch 2.0 instances; the error is as follows:
```error: check.go:578: no Elasticsearch node available```

What is the timeline for supporting this new official version? What is involved in doing so?

**Comment by captncraig** [comment]
Do you know if v3 will be backwards compatible with old clients? We can start by updating the package and see where that takes us.

**Comment by awesensepaul** [comment]
I don't think it is backwards compatible, unfortunately. I may have done this incorrectly, but I replaced:
```src/bosun.org/_third_party/github.com/olivere/elastic``` with the `v3` version as obtained by:
```go get gopkg.in/olivere/elastic.v3```

I see the following errors when I try to build:
```expr/logstash.go:74: s.Indices undefined (type *elastic.SearchService has no field or method Indices, but does have elastic.indices)
expr/logstash.go:90: multiple-value r.Source.Source() in single-value context
expr/logstash.go:97: multiple-value req.Source.Source() in single-value context
expr/logstash.go:354: undefined: elastic.NewRangeFilter
expr/logstash.go:355: undefined: elastic.NewFilteredQuery
expr/logstash.go:365: undefined: elastic.FilteredQuery
expr/logstash.go:367: undefined: elastic.Filter
expr/logstash.go:378: undefined: elastic.NewRegexpFilter
expr/logstash.go:389: undefined: elastic.NewRegexpFilter
expr/logstash.go:394: undefined: elastic.NewAndFilter
expr/logstash.go:394: too many errors```

**Comment by captncraig** [comment]
right. I'll give a shot at updating the api. I'm not worried too much about that. I'm mostly concerned with compatibility on the wire. Can the new client talk to an old server?

**Comment by awesensepaul** [comment]
I think the HTTP protocol should be compatible.

Here is the author's list of API changes:
https://github.com/olivere/elastic/blob/release-branch.v3/CHANGELOG-3.0.md

**Comment by deanefrati** [comment]
Do you guys have an estimate of when elastic 2.x will be supported?

**Comment by aodj** [comment]
Is there any movement on this issue that might not be being tracked in this issue?

**Comment by kylebrandt** [comment]
Not yet :-/ still on my mind though

**Comment by kylebrandt** [comment]
Elastic 2.0 has breaking changes, so the particular Go library we are using decided to fix some things by introducing their own breaking changes. So, it only seems logical that now is a good time for bosun breaking changes as well....
I have the following in mind currently and am looking for feedback:

```lscount(indexer ESIndexer, csvKeys string, query ESQuery, bucketSize string, startDuration string, endDuration string)```

indexer will be a function that returns an new ESIndexer - this will allow us to support different index schemes that people need as they can add new functions that return an ESIndexer. The default one will append dates like it does now (or maybe take a date fmt string for days). This fixes https://github.com/bosun-monitor/bosun/issues/974 in a more robust way.  This can still be in most queries since it can be a global variable in the config (although maybe a bit annoying when it comes to the expr page or using external UIs like Grafana).

The second argument, csvKeys, are the elastic fields to run a terms + date histogram on. I would remove the filtering ability from this string that exists in the current version. All filtering is then done in the next argument. This is maybe a little less terse, but will result in more query power. Regex is limiting (https://github.com/bosun-monitor/bosun/issues/1479 , https://github.com/bosun-monitor/bosun/issues/1525) and with numeric fields in ES 2.0 it even throws a type error.

The third argument will be a function that returns an ESQuery. In the initial release I will aim to add a few base Query types (bool, regex, range) as bosun functions. Some functions will also take ESQueries as arguments, such as bool. Bosun's lack of vargs will be annoying here, but I think I can work around it. My hope is this design lets us expand what elastic filters we support over time.

This of course all assumes I'm able to code this :P
