### ISSUE TITLE
scollector: Auto-discover non-default instances of SQL Server

### ISSUE THREAD

**Issue by floyd-may** [bosun-monitor/bosun#1523]
I'm not getting SQL Server monitoring from instances of SQL server whose instance name isn't the default, "MSSQLServer".

From [code-surfing here](https://github.com/bosun-monitor/bosun/blob/master/cmd/scollector/collectors/sql_windows.go), it appears that the WMI queries are generated from the struct names, which correspond to WMI class names (I think?). If so, that doesn't work for named instances of SQL Server. If your instance name is `DERP`, rather than getting general stats from a WMI class named `Win32_PerfRawData_MSSQLSERVER_SQLServerGeneralStatistics`, you get them from a class called `Win32_PerfRawData_MSSQLDERP_MSSQLDERPGeneralStatistics`. Fun :confused:

**Comment by floyd-may** [comment]
Bueller?

**Comment by gbrayut** [comment]
This was also on my list... I think we were going to look at opt in monitoring of named instances. The different WMI class names make it a bit tricky, and they may end up needing to be under a different namespace (mssql.instance.*). I'll take another swing at it and let you know later this week what I find.

**Comment by floyd-may** [comment]
Thanks, and sorry for being a pest =)

What's the rationale for putting it under a different namespace? That seems like a prime example of what tags are for. If there's only ever one instance per host, regardless of whether or not it's the default instance, I would expect a given metric query to Just Work (tm). If I have to alter the metric query based on some sort of out-of-band knowledge that some instances are configured with the default name and some aren't, that seems strange. If I need to break it down by instance, I can add the tag to the query.

**Comment by gbrayut** [comment]
We often are a bit tag heavy on Bosun (most opentsdb instances use much more verbose metric names instead of lots of tags) and it has hurt us before (our os.net.bytes metric is so slow we had to denomalize it into __hostname.os.net.bytes for queries that return more than one day of data), so I just have a knee jerk reaction on some of these.

It does fit the tag model pretty well, so I'll try and get it in that way. In my defense named instances do often behave differently at a networking/firewall level (ever tried to setup saved network credentials in windows for one?), which is one reason why we only use the default instance here at Stack Overflow. I've used them a bunch in the past and they work great for development, so I'll see what I can do.

**Comment by floyd-may** [comment]
No argument here about the pain that named instances cause =)

**Comment by VictoriaD** [comment]
Has any progress been made with this one? In the meantime, is there a way to manually configure scollector to look for these statics?

**Comment by gbrayut** [comment]
Still haven't gotten time to work on this yet. The only progress we've made is installing a named instance on a test system so we can start changing the collector to support named instances.

There isn't any way to manually set this up, since all the WMI class names change for each named instance you create.

**Comment by VictoriaD** [comment]
I was doing some more testing of the version I put together to address this issue, and discovered that my version didn't work on an instance with an underscore in the name. It turns out that you need to remove additional underscores from the WMI class name as well. So if your sql instance is called `DERP_A`  your wmi class for `Win32_PerfRawData_MSSQLSERVER_SQLServerGeneralStatistics` does not become `Win32_PerfRawData_MSSQLDERP_A_MSSQLDERP_AGeneralStatistics`, it becomes `Win32_PerfRawData_MSSQLDERPA_MSSQLDERPAGeneralStatistics`.

I've updated my pull request with these changes so it's up to date.

**Comment by gbrayut** [comment]
fixed in #1671
