### ISSUE TITLE
scollector: Log when root is needed

### ISSUE THREAD

**Issue by floyd-may** [bosun-monitor/bosun#1539]
I'm attempting to monitor specific processes on a linux box; however, I'm getting no stats. I am, however, getting tagged stats for process count (linux.proc.count) for each of the processes I'm attempting to monitor, just no runtime stats (linux.proc.cpu, e.g.).

Sample from my TOML file:

```
[[Process]]
  Command = "bosun-monitor"
  Name = "bosun"
  Args = ""
  IncludeCount = true
```

Without the `IncludeCount = true` I get nothing at all. I added it in the process of debugging. Not seeing anything in the log, even with debug output.

**Comment by gbrayut** [comment]
try omitting the `Args = ""` line. We use the following for monitoring the bosun process and generating linux.proc.* stats with name=bosun tags:
```
[[Process]]
  Command = "/opt/bosun/bosun"
  Name = "bosun"
```
assuming your program is bosun-monitor instead of just bosun, your settings should work but the empty args might be causing issues.

The `IncludeCount = true` was added in https://github.com/bosun-monitor/bosun/pull/1316 as an optional way to track how many processes are matching the command/args specified. We use the same toml file on all hosts, so we don't track the count since it would add a lot of zeros for processes that only run on certain systems. 

Also read through http://bosun.org/scollector/process-monitoring if you haven't yet, as there are some gotchas on how Command and Args work. If it still isn't working try `ps aux | grep [b]osun` and see if it returns anything.

**Comment by floyd-may** [comment]
Hi Greg, thanks for responding so quickly. I appreciate the work you are doing with bosun & scollector :+1: 

I'm doubtful that the empty `Args` parameter is the issue, for two reasons. First, here is another example from my scollector.toml that is also not working, and its `Args` is non-empty:

```
[[Process]]
  Command = "java"
  Name = "opentsdb"
  Args = "opentsdb.tools.TSDMain"
  IncludeCount = true
```

Second, given that these two processes are the only ones in my scollector.toml, I'm getting `linux.proc.count` stats for them, with the names that I've configured. Both processes show a count of 1 since yesterday afternoon when I added the `IncludeCount = true`, which reflects reality: they've been up the whole time. I'm just not getting any of the other `linux.proc.*` stats. It seems to be properly matching the process name & args (especially given that I've got lots of other java processes on this box), but not collecting performance stats properly.

I've also got verbose logging turned on, but I haven't seen anything in the log that reveals what the issue might be.

Again, thanks for the help. I'm actually suspicious after looking at the contents of `collectors/processes_linux.go` and poking around in the `/proc` filesystem that maybe the issue is scollector not having enough permissions to read all the files there. I'll report back with what I discover.

**Comment by floyd-may** [comment]
AHA! That was it. Running scollector as root solves the issue. Some better logging around this would be helpful, it appears that the error is checked for non-nil and then sent to the bit bucket:

```
io_file, e := ioutil.ReadFile("/proc/" + pid + "/io")
if e != nil {
	w.Remove(pid)
	continue
}
```

**Comment by gbrayut** [comment]
good catch. I think the error is discarded since the pid could be for a process that has already exited. I'll talk with Craig about adding a warning about not running as root or Administrator as that will likely cause many collectors to stop working.
