### ISSUE TITLE
Unable to `go get`

### ISSUE THREAD

**Issue by phemmer** [bosun-monitor/bosun#1556]
I'm trying to use the `bosun.org/snmp` package, but go get fails:

```
# go get -d -v
Fetching https://bosun.org/snmp?go-get=1
ignoring https fetch with status code 404
Parsing meta tags from https://bosun.org/snmp?go-get=1 (status code 404)
import "bosun.org/snmp": parsing bosun.org/snmp: http: read on closed response body
package bosun.org/snmp: unrecognized import path "bosun.org/snmp"
```

This can be reproduced with a very simple source file:

```
# cat main.go 
package main

import "bosun.org/snmp"
```

**Comment by captncraig** [comment]
dang, not this again. An issue with the go tool makes our setup a bit tricky. You can workaround for now by using `go get -insecure bosun.org/snmp`.

The fix for reading metadata on 404s should be in go1.6 at which point the whole thing should work much smoother. I'll also try to create the necessary doc file to make it work.

**Comment by captncraig** [comment]
I pushed a change to the `bosun.org` site that I hope fixes this. Can you confirm?

**Comment by phemmer** [comment]
Aye, working now. Thanks.
