### ISSUE TITLE
Function returning a constant-valued time series

### ISSUE THREAD

**Issue by gnosek** [bosun-monitor/bosun#1655]
I'd like to graph the current alert threshold along with metric values. Can I pretty please have a function that returns a time series containing a stream of constant values?

**Comment by kylebrandt** [comment]
Will be something like:

`hline(number, "tagkey", startDuration, endDuration)`

And will return a series with tagged with the tagkey. Will return a series with two datapoints, and (now-StartDuration, number) and (now-endDuration, number). Stream isn't needed since to draw a line you just need two points.

**Comment by gbrayut** [comment]
can we generalize it to just `line(startNumber, endNumber, "tagkey", startDuration, endDuration)`?

**Comment by kylebrandt** [comment]
Use case for that?

**Comment by gbrayut** [comment]
wanting to show a linear increase of a noisy metic. Like linelr but manually specifying values

**Comment by gbrayut** [comment]
Id also rather see one line function than hline() and slopeline()

**Comment by kylebrandt** [comment]
Can use the series func to do this now.
