### ISSUE TITLE
Expose checkFrequency and runEvery configurations in rules

### ISSUE THREAD

**Issue by vitorboschi** [bosun-monitor/bosun#1656]
This would enable rules to use a time span dependant on the frequency, thus not missing data points between two checks.

Ideally, the user should be able to create a variable like:
$timespan = d($checkFrequency) * $runEvery * 1.5

and use it as a parameter to q()

Concerns raised by @kylebrandt :

1. q() currently expects a string, so you couldn't use $timespan directly.
2. What would be the value of runEvery in the Expressions page?

For 2., I think a reasonable solution would be to use the value of defaultRunEvey configuration

**Comment by kylebrandt** [comment]
If the above gets merged, you could do the following:

```
hostname = bosun.ds.stackexchange.com
tsdbHost = ny-tsdb01:4242
tsdbVersion = 2.2

$checkFrequency = 1m
checkFrequency = $checkFrequency
$defaultRunEvery = 5
defaultRunEvery = $defaultRunEvery


template test {
	subject = {{.Last.Status}}: {{.Alert.Name}} on {{.Group.host}}
	body = `<p>Name: {{.Alert.Name}}
	<p>Tags:
	<table>
		{{range $k, $v := .Group}}
			<tr><td>{{$k}}</td><td>{{$v}}</td></tr>
		{{end}}
	</table>`
}

macro defaultRunStart {
    $start = tod(d("$checkFrequency")*$defaultRunEvery)
}

alert test {
	template = test
	macro = defaultRunStart
    crit = avg(q("avg:rate:os.cpu{host=*bosun*}", $start, ""))
}
```

This uses global variables. If the alert has a different check frequency, you wouldn't use the Macro and instead make a different variable for runEvery (since we don't override vars). Macro is optional.

Global variables are available in the expression page, so this would eliminate any special handling to make things work on the expression page.

**Comment by vitorboschi** [comment]
That's good news! Thanks Kyle

**Comment by kylebrandt** [comment]
In master now, so closing.
