### ISSUE TITLE
Bosun Alerts Configuration

### ISSUE THREAD

**Issue by dileepindla** [bosun-monitor/bosun#1682]
Hi Team,

We are configuring alerts in Bosun. We are facing below mentioned issues. 

1) We have configured alert with name  "bosunalert " in my dev.conf file and started bosun. But i observed that still it is triggering my old alerts also  . Will you please help me how to delete my old alert. Else please let us know from  where these old alerts are picked from ? For more details please refer below logs .

```
info: check.go:537: check alert test done (2.498635ms): 0 crits, 0 warns, 0 unevaluated, 0 unknown
2016/03/25 10:59:33 info: alertRunner.go:55: runHistory on mytest took 107.91µs
2016/03/25 10:59:34 info: notify.go:115: relayed alert bosunalert{} to [dileepindla@***.com] successfully. Subject: 30 bytes. Body: 94 bytes.
2016/03/25 10:59:43 info: notify.go:115: relayed alert mytest{} to [dileepindla@***.com] successfully. Subject: 30 bytes. Body: 94 bytes.
```

2)  I have a requirement when a host is down i need to raise an alert.Installed TCollector on each host . For this i can use a metric named "proc.uptime.now" which will say host is up or not. Now when the host is down i don't get any values for this metric.
Can you please let me know how to write this  condition to check empty or null value
If the host is down query - **avg(q("sum:rate{counter,,1}:proc.uptime.now{host=*}", "1h", ""))** will return  empty or null . How to write a condition  to raise an alert ?
We tried with below query but not able todo much .

```
$q = avg(q("sum:rate{counter,,1}:proc.uptime.now{host=*}", "1h", ""))
crit =$q<1
critNotification = email
```

3) I have one more requirement where i need to monitor 600 hosts . Will you please let me know is there any way to monitor with  common approach ? Or Is there any way i can integrate DB ? So that it will pick host name and email ID dynamically .

**Comment by pavanshetty05** [comment]
If the host is down always query will return null value . Do we  have any option to test it  ?

**Comment by kylebrandt** [comment]
1. Are you on latest 5.0 RC2? If you have removed an alert from your config, and restarted bosun, and it is still firing that is a bug. Bosun should clear alerts that don't exist any more on start.

2. When data stops coming in for a tagset that you have defined an alert on it, it will trigger an "unknown" state. So you don't have to create an alert like this. If you would rather it go warn or crit, you can do something like `since(q(... "12h", "") > d("5m")`. That will trigger after 5m, but after 12h it will still go unknown.

3. I don't understand the first 2 questions here, but we have about 500 hosts and we use OpenTSDB and it works fine. When it comes to notifications based on tags you can use notification lookups:

```
lookup host_base_contact {
    entry host=nyhq-* {
        main_contact = it-alerts
        chat_contact = it-bonfire-chat
    }
    entry host=* {
        main_contact = default
    }
}

alert .... {
    warnNotification = lookup("host_base_contact", "main_contact")
    critNotification = lookup("host_base_contact", "main_contact")
    warnNotification = lookup("host_base_contact", "chat_contact")
    critNotification = lookup("host_base_contact", "chat_contact")
}

```

**Comment by msqiao** [comment]
您好，你有bosun设置告警策略如果产生告警发邮件的例子吗？？？如果通过Java修改策略的话，如何去修改呢？是不是只能通过配置文件修改呢？我是通过bosun的二进制文件安装的，谢谢你了，能帮我解答一下吗？跪谢！！！
