### ISSUE TITLE
Cache for query

### ISSUE THREAD

**Issue by cleonte** [bosun-monitor/bosun#1757]
Hi,

When using opentsdb some of the queries where cached so if you shared a query link with someone the result would be faster for second access, can you implement something like this for bosun also?  

Cheers

**Comment by kylebrandt** [comment]
Bosun does this already (see cmd/bosun/cache). So queries will hit the cache when they are the same. In practice this means the time of the query has to be the same since the key is the generated opentsdb query. 

So when you use the testing page or expr page and are iterating on something, I suggest you set the time. Alt-P in the UI brings up miniprofiler, and you can see how long queries take. If you have set the time and repeat the queries, you should see the they are much faster.
