### ISSUE TITLE
[FEATURE REQUEST] add host graphing and listing with graphite backend

### ISSUE THREAD

**Issue by xinity** [bosun-monitor/bosun#1829]
hi guys,

i've seen that hosts and graphs are only displayed in bosun if stored in openTSDB.

any ways to implement this with graphite backend ? 
we use graphite to store our hosting platform metrics and we'd like to use bosun as an alerting system.
Not being able to see hosts and graph in Bosun is needed (at least until grafana fully implements alerting through bosun).

hoping this feature request is easy to implement,

**Comment by gbrayut** [comment]
We don't have any plans to implement this right now, but would be happy to accept a pull request for this feature. It may be a bit difficult since for openTSDB it only works if you send a copy of the data to Bosun as well so it can be indexed. For Graphite we'd probably want to use their API to enumerate the possible metrics instead.

**Comment by Dieterbe** [comment]
with graphite this is pretty hard because it's so un-standardized:
1) there's a bunch of different agents that report the data with different metrics (both how the metrics are called as well as how the data is reported)
2) you can typically configure your agent with different metric prefix or naming schemes
3) collectd in particular has an option i hate: storeRates, which changes the reported data (it basically derives it), but under the same given key

all these things mean it becomes very difficult to "just provide graphite dashboards that query the right data and visualize it the right way".

with Grafana we "solve" 1 by just providing different dashboards for different agents and we will solve 2 by letting people finetune their prefix and naming scheme. and 3 for now will be "solved" by just stating which setting we're compatible with.
example : https://grafana.net/dashboards/24

if anything i think we should take this stuff out of bosun and move it into grafana (also for opentsdb)

**Comment by xinity** [comment]
@Dieterbe @gbrayut thanks for your replies

how we can go on , on this ?
should i put should work on this ? i'd be happy to try :)
