### ISSUE TITLE
Scollector running as a service on Windows doesn't log panics

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1867]
It appears that when Scollector is running as a service on Windows it doesn't log panics anywhere. We probably should find a way to send them to the event log or file system.

Currently the only event that occurs is:

> Log: System
> Source: Service Control Manager
> Event ID: 7031
> The scollector service terminated unexpectedly.  It has done this 1 time(s).  The following corrective action will be taken in 60000 milliseconds: Restart the service.

Also restarting the service automatically is not enabled by default (that is configured by DSC in our environment), so that last sentence probably won't appear in other environments unless they configure the service recover actions:

![image](https://cloud.githubusercontent.com/assets/304401/17638578/40b6c4a8-60a8-11e6-8856-1f6c9c8cd658.png)

It would be nice to get those recovery actions added in the service_windows.go installation method.

**Comment by captncraig** [comment]
The event log only gets stuff that goes through slog right? Panics wouldn't call that, just write to stderr. 

My first instinct was to wrap main in another function to defer/recover.  That is not sufficient though, since panics from other goroutines would not get caught in that recover. 

Every goroutine that scollector launches with `go` would need a corresponding `recover/slog/fatal` deferred.
