### ISSUE TITLE
Please document the templating language

### ISSUE THREAD

**Issue by badp** [bosun-monitor/bosun#1892]
The Bosun templating language seems to be able to do [great things](https://bosun.org/examples#graphite-verify-available-cluster-cpu-capacity). It's unclear what it can actually do, though, because I can find literally no documentation anywhere about this, just the example page for our cargoculting pleasure :(

I see that some has already been written [here](https://github.com/bosun-monitor/bosun/blob/34b8f87e9d9fce5902817aae6626fed4ab829901/docs/configuration.md) (helped me finally come up with `{{ replace $f.Group.fully_qualified_hostname_but_with_underscores_instead_of_dots "_" "." -1 }}`) but that page appears to be nowhere where Google can easily find it :/

**Comment by kylebrandt** [comment]
Docs are pretty bad when it comes to templates. The current documentation for template functions is in http://bosun.org/configuration under "Functions Available to alert templates" but it isn't very good or complete.

Since 0.6.0 splits the rule / template / notification etc config from the system config, I need to redo this for the 0.6.0 release anyways, so I have made it part of the Milestone.

The three template topics under http://stackoverflow.com/documentation/bosun/topics might be helpful in the meantime in addition to what current exists under bosun.org/configuration.

Also in the meantime most of the functions available in templates are on in the root sched.Context in https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/sched/template.go . Some of the builtin template funcs always available are at https://github.com/bosun-monitor/bosun/blob/e40f876dd5048d804f6900334cab11a4244f9fae/cmd/bosun/conf/rule/rule.go#L382

**Comment by gbrayut** [comment]
They are also based on Go templates, so https://golang.org/pkg/html/template/ is another good starting point.

**Comment by kylebrandt** [comment]
@badp I'm some 40 commits in and not done: https://github.com/bosun-monitor/bosun/pull/1940 . Even though we did this technical debt to ourselves, I'm going to project the blame on to you and never forgive you :-P

**Comment by kylebrandt** [comment]
fixed in https://github.com/bosun-monitor/bosun/commit/d587acfc36b77a673118b8a99cdecc75128810ca
