### ISSUE TITLE
Feature req - function to count groups

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1908]
Right now best way to do this is `len(tr(q(...),""))`, which is a bit weird.

**Comment by kylebrandt** [comment]
You example is not quite correct, `q(..)` need to be in a reduction function, as the first argument to `t()` takes a numberSet, not a seriesSet. When it comes to getting the total items in the set, the aggregation doesn't matter, but in other cases is does.

As I look through our config, we often don't use "count the number of items in a set in isolation".

So what I see is a slippery slope of convenience functions here. Since this in SQL is is something like:

```SELECT Count(*) From SET``` when you also often Sum(), Avg(), and different groupby statements. 

So I'm inclined to reject this without better user stories.

**Comment by gbrayut** [comment]
You are correct, `len(t(last(q(...)),""))` is the correct syntax that Jason and I stumbled upon when this issue came up, and it is something that usually takes a few tries to get right anytime I need it. My first instinct is to try count, then len, then I remember you have to jump thru a few hoops to get what you want.

We have a lot of functions that only work on certain inputs, and for a while we've just jumped thru whatever path is required to get there, but even from just a readability stand point this makes it more difficult to understand what an alert is doing. A countSeries(q(...)) or whatever would make that much clearer. And back to a SQL analogy this seem much closer to the row count, which is basically metadata that gets returned with all queries unless you set the no count option.

Agree it is low priority since we have a workaround, but we should at least be tracking these so we know which ones cause the most difficulties.

**Comment by gbrayut** [comment]
Specs work for me, but I know we've have multiple issues like this come up that have gotten lost. Thoughts on just starting a "DSL Improvements" label to slap on these issues as they come up?

**Comment by kylebrandt** [comment]
Yes, I'd call it expr though since it matches the package and routes etc. We have one for lexer changes, but that is really for things that require a change to the language, not just new functions. 

Another useful tag might be "needs more spec" - which could mean either user stories and a tech plan. Or we could have a label for each. That would really help sort out the status of issues / PRs.

**Comment by kylebrandt** [comment]
Edited the label to be DSL improvements - that is a better name. Expr vs Parse Lexer etc assumes that the implementation of what is needed is known. Bad assumption.
