### ISSUE TITLE
Alerts using multiple Elastic indexes with the same timespan will have cache conflicts and return invalid results

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1926]
Currently it looks like the bosun cache doesn't account for which index is being used in an escount query, only the timespan, bucket size, and the field name. You can run an escount(esdaily("CreationDate", "fastly-", "2006.01.02"), ....) query on the expression page and then change the index to "trafficlogs-" or even "thisindexdefinitelydoesntexist" and you still get the same results from the previously cached query.

This causes issues when you try to use multiple indexes in an alert as they will all return the exact same results if the time span and field name is the same. There are a few more details in our [SRE Chatroom](http://chat.meta.stackexchange.com/transcript/message/5320725#5320725).

The current workaround is to vary the time span or bucket size a bit for each index queried.

**Comment by kylebrandt** [comment]
I think this doesn't have an "easy" fix that is acceptable performance wise (not in terms of numbers, but just plain old decency) to fix this.

The bug is that the indices are not taking into account when generating a cache key (There is also an unused CacheKey function which is just sloppy). So if you have the same query but to different indices, bosun will incorrectly regard those as the same item, cache the results of one, and return that result for both requests. 

Some thoughts before I forget:

Currently we have various functions that return Indexers. Indexers are called at the same time of the query. 

Indexers basically:

1. Ask elastic for all the indexes
2. Use the arguments provided to Indexer creation functions to select which indices should be queried with various logic depending on the indexer func used.

This was already bad because we keep asking for all of the indices.

So I believe what we need to is to cache the indices as a separate cache item so we don't keep hitting them over and over again. The question is what level to cache at. 

Since all indexers when called to generate indices have to fetch all the indices. I could fetch those if I could think of a clean way to know when to invalidate them.

I could also maybe change the logic to see which indexes "could exist" based on the indexer, and check to see if those exist. I could then put them into the cache as I discover them. If all the indexes I might need are in the cache I'm good to go, if not then I can check for the specific indices I need.

Either way indices should probably have their own cache since they should have a longer lifetime in general than queries would.

Not sure what to do yet, need to let this soak in.

**Comment by kylebrandt** [comment]
Too much data not to cache based on how indices are currently fetched:

```
# kbrandt at ny-bosun01.ds.stackexchange.com in ~ [14:57:51]
$ curl -XGET 'http://ny-lselastic01:9200/_all' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 34.9M  100 34.9M    0     0  27.8M      0  0:00:01  0:00:01 --:--:-- 27.8M
```

**Comment by kylebrandt** [comment]
2 new ideas:

1. Turns out there is an option to ignore missing indices (unless there are none). So I don't even need to request the list of existing indices I don't believe, which is awesome. https://www.elastic.co/guide/en/elasticsearch/reference/current/multi-index.html 
2. Elastic supports time ranges https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html (date math) for index names

So with the first item, I don't even need to fetch the indices, can just provide what should be there and let elastic handle it.

With the second item, I may not even to do any generate logic if the use cases I need are covered.

**Comment by kylebrandt** [comment]
Plan:

- Redo ES daily to generate the dates that should exist based on the request time
- Stop fetching the list of indices
- Include the indices that should exist in the cache key (If an index has been added or removed that fills a gap this might not show up due to *query* cache hits, but I don't care right now I don't think) 
 - Fix error reporting so it shows the full elastic error. Currently it only shows the first line. Which has not only been annoying in other cases, but will be even worse here since I'm now counting on elastic to return "no such indices" instead of doing it the code myself
 - Update the ESMonthly PR to use the above new method

This eliminates the need to fetch indexes at all, a 35MB request that takes about a second that we are doing over and over again currently.

For now I'm not going to mess with elastic's date math because I would either have to translate the formatting codes to Go format's code, or change the existing functions (or add new ones).  Starting from scratch I probably would have not done this because I need other libraries to get month / week truncating, but I'm already vendoring those anyways. I can change my mind here later anyways if needed.
