### ISSUE TITLE
set environment variable for redis connection

### ISSUE THREAD

**Issue by lazywhite** [bosun-monitor/bosun#1928]
no doc found to show how to set envrironment variables of redis connection,  please update the documentation

**Comment by lazywhite** [comment]
it seems like I should set envrionment variable as a Bash exported variables, then use it in bosun.conf like this   
```
redisHost = ${env.REDIS_HOST}
redisDb = ${env.REDIS_DB}

```

**Comment by kylebrandt** [comment]
The TOML file doesn't support environment variables like the definitions /
rule conf file does.

The reason for environment variables there was:

   - You could see the values in the UI
   - Might accidentally copy part of a sensitive config when getting help
   with alerting rules etc

Since the new system config file is smaller and doesn't contain rules so in
the case of keys etc are just in the file.
