### ISSUE TITLE
WIP: Improving HTTP Post notifications in Bosun

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#1952]
Currently working on spec'ing this. Will probably end up in 0.7 (vNextNext - after auth). The Google doc is view only:

https://docs.google.com/document/d/1e9mhfD1aLR78sxxJXL2X7T3ujGPFX4-GzAyCdOVwXzY/edit?pli=1# 

But feedback and thoughts can be left here if you like.

**Comment by ayashjorden** [comment]
Testing notifications feature is very important and can save a lot of dev time.
So sending the POST/GET notification to the configured endpoint and not just display the payload will serve us better

See the [Slack](https://bosun.slack.com/archives/general/p1478645232002792) message.

**Comment by angadsingh** [comment]
just went through this doc after already having commented here: https://github.com/bosun-monitor/bosun/pull/1737#issuecomment-303719268

suggestions/ideas:

* instead of opening up the template definition completely with arbitrary variables, how about having "template types" for each kind of notification. please read the complete suggestion here: https://github.com/bosun-monitor/bosun/pull/1737#issuecomment-303719268
* why can't bosun "resolve" the pagerduty incident when the bosun incident's severity decreases to normal (i.e. recovery notifications). This would go a long way in reducing alerts and alert fatigue - right now we need to set a low (1 hour) timeout in the notification chain (self) so that it retriggers. That's because we are using the repeated trigger as a way to come to know when the incident resolves, causing high number of repeats for the same incident.
* we do have a reverse integration written for PD to bosun (i.e. ack/resolve/close bosun incident when a human acks/resolves it in PD). if its alright we can share it with the bosun project. it has both incoming webhook and polling based (if you're behind a firewall) integration. it currently works with sending the `subject` of the alert as the PD `incident_key` which is then parsed back to get the bosun incident ID.
* if we're worried too much about template repetition, apart from simple template inclusion using {{template "name"}}, golang templates also supports template inheritance via "blocks" - and it does work in bosun, albeit with a catch. e.g. 

`template base {
     subject = ```This is a template which can support inheritance. {{block "alpha"}}This is the default text{{end}}. My other text.```
}

template child {
    subject = ```{{define "alpha"}}This is the replaced text{{end}}{{template "base" .}}```
}
`

The catch is that bosun seems to be using the same template context across alerts, so when there are multiple alerts using the same "base" template, the child override overrides for them too

**Comment by kylebrandt** [comment]
Will be fixed with https://github.com/bosun-monitor/bosun/pull/2135
