### ISSUE TITLE
No way to test Bosun notifications from the UI

### ISSUE THREAD

**Issue by dbkaplun** [bosun-monitor/bosun#1956]
Currently there is no way to determine if Bosun is triggering notifications via the UI. Even though I am able to see the compiled template, graphs, etc, I am not getting notifications for email, Slack, or PagerDuty although I've set them up in the alert. (I get an email if I manually input my email address into the UI but that is not the same.)

**Comment by gbrayut** [comment]
As we look at expanding http notifications and moving some of the template/markup into the notification definition it will become more important to be able to test the full pipeline instead of just the template or sending to a specified email address. Maybe letting you specify a notification you want to use for testing instead of just an email address.

**Comment by kylebrandt** [comment]
Will be fixed in https://github.com/bosun-monitor/bosun/pull/2135
