### ISSUE TITLE
Adding Percentiles Aggregation options to elastic search functions

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#1968]
The [esstat](http://bosun.org/expressions#esstatindexroot-esindexer-keystring-string-filter-esquery-field-string-rstat-string-bucketduration-string-startduration-string-endduration-string-seriesset) function currently supports avg, min, max, sum, sum_of_squares, variance, and std_deviation and is based on the [Extended Stats Aggregation
](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-extendedstats-aggregation.html)

We have a percentile function that returns single values for each series in a set, but there is no way to get a p95 or p99 from elastic. Elastic supports [Percentiles Aggregation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-aggregation.html) and [Percentile Rank](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-percentile-rank-aggregation.html) which would come in handy when alerting on traffic logs (bytes, duration, etc)

**Comment by kylebrandt** [comment]
Yes this has been on mind. In particular since that is a query I end up
switching from Bosun expressions to the Grafana UI when I want to display
it in Grafana.

The the thing that has been making me hesitate is indecision around being
able to query for multiple percentiles. That could be useful to display in
alert or dashboard, but isn't a return type really. Would probably be a lot
more efficient to get percentiles in one query when wanting multiple.

Also might be associated with histogram work.

**Comment by gbrayut** [comment]
esstat doesn't supports multiple rStat options right now either, so if you wanted to use more than one you would probably have to merge the series. For alerts you usually don't need multiple, but I can see it being nice for grafana or other dashboards.

**Comment by kylebrandt** [comment]
Yes, I have done that in Grafana in terms of merging. The thing is
percentile queries are very expensive on our logs, so doing multiple and
merging them might be a lot slower since elastic itself can query multiple
percentiles in the same query.
