### ISSUE TITLE
Deprecated metrics seem to stick in Items page indefinitely

### ISSUE THREAD

**Issue by alienth** [bosun-monitor/bosun#1969]
Metrics which haven't received datapoints in over a year are showing up in the items page. This can cause usability issues which metric namespaces change, as it is difficult to determine what metrics are actively used.

**Comment by kylebrandt** [comment]
https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/web/static/js/graph.ts#L433

and

https://github.com/bosun-monitor/bosun/blob/master/cmd/bosun/web/static/js/items.ts

needs fixing. Should be coming from the system searchsince config param I think which is or should be added to values injected into the rendered index.html unless that has changed with auth

**Comment by alienth** [comment]
Might be worthwhile to display these, but sort them to the bottom? That way you know they are there and can consider separately wiping the datapoints associated with em.

**Comment by kylebrandt** [comment]
I'd kind of rather just remove the items page :P

**Comment by IzakMarais** [comment]
The Bosun items page is very useful, especially since there is no real OpenTSDB metric exploration or tree view in Grafana.

**Comment by kylebrandt** [comment]
If people find it useful I don't mind keeping it.

If you are having bosun index your data. The bosun Grafana plugin has
metric and tag autocompletion under the OpenTSDB query helper...

But that still isn't a list view

On Nov 30, 2016 01:35, "Izak Marais" <notifications@github.com> wrote:

The Bosun items page is very useful, especially since there is no real
OpenTSDB metric exploration or tree view in Grafana.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/bosun-monitor/bosun/issues/1969#issuecomment-263795252>,
or mute the thread

**Comment by kylebrandt** [comment]
This has been fixed IIRC
