### ISSUE TITLE
How to trigger a notification when an alert is unknown, which cannot be evaluated

### ISSUE THREAD

**Issue by xufeibuaa** [bosun-monitor/bosun#2038]
I only find warnNotification and critNotification. 
Please help ...

**Comment by gbrayut** [comment]
When the queries used in crit or warn do not return any results, the alert will become unknown. Because there is limited information available, unknown notifications use a different template (see http://bosun.org/definitions#the-unknown-template ). They will however send the message to the existing warnNotification or critNotification defined for the alert. You can configure how long the return results should be missing before it triggers by adding `unknown = 30m` to the alert (see http://bosun.org/definitions#unknown )
