### ISSUE TITLE
Auto timeout for acknowledged alerts

### ISSUE THREAD

**Issue by angadsingh** [bosun-monitor/bosun#2086]
Currently, acking alerts stops any notification chains from repeating, **indefinitely**.

To avoid this, we actually have a cron job in-house, which auto force-closes alerts which have been acked for more than X hours, to avoid a situation where a human acked and then forgot about the alert.

Instead, it would be nice to have an auto-timeout for acknowledged alerts. Even pagerduty has the same (auto resolve acknowledged incidents after X time) - second option in attached screenshot. First one is what notification chains do in bosun already.
<img width="1141" alt="screen shot 2017-05-24 at 4 03 50 pm" src="https://cloud.githubusercontent.com/assets/1623026/26399495/c4bb59f8-409a-11e7-96ef-9f24ea270249.png">

**Comment by kylebrandt** [comment]
I understand the use case, but this is a feature I don't see us adding any time soon. With our current development resources and priority the state machine for alerts can't take any more complexity :-/

If we were to do it, I would probably do the following:

- If the Ack UI/API, let a timeout be specified on Ack. Infinite would be option
- Then the behavior as you basically described

This is basically how the Delayed close feature in master works. I ended up doing a forceclose there as well because of the state complexity, and even that turned out to be pretty hard / time consuming to get done safely.
