### ISSUE TITLE
Not able to post bulkedit

### ISSUE THREAD

**Issue by paul-arpan** [bosun-monitor/bosun#2117]
Hey,

I have added a UI layer which can directly access the config file. I am not able to post to the /api/config/bulkedit.

My post call is in this format.
{	
	
	"EditRequest" : [{
				   "Name":"email5",
				   "Type":"notification",
				   "Text":"notification email5 { email = abcd@example.com}",
			           "Delete": false

				}]

	}

But I keep getting the 
"json: cannot unmarshal object into Go value of type conf.BulkEditRequest" error. Kindly help me out.

**Comment by kylebrandt** [comment]
Be warned, this bulk edit feature is "experimental" and not something we actually ended up using. That being said it may work fine, but be aware you in a bit of uncharted territory.

A `conf.BulkEditRequest` is a slice of EditRequest:

```
// BulkEditRequest is a collection of BulkEditRequest to be applied sequentially
type BulkEditRequest []EditRequest

// EditRequest is a proposed edit to the config file for sections. The Name is the name of section,
// Type can be "alert", "template", "notification", "lookup", or "macro". The Text should be the full
// text of the definition, including the declaration and brackets (i.e. "alert foo { .. }"). If Delete
// is true then the section will be deleted. In order to rename something, specify the old name in the
// Name field but have the Text definition contain the new name.
type EditRequest struct {
	Name   string
	Type   string
	Text   string
	Delete bool
}
```

So your body should just be an array of those objects at the root. *Not* a dictonary at the root (and there is no EditRequest key either).

So I think it should just be:

```
[{
			   "Name":"email5",
			   "Type":"notification",
			   "Text":"notification email5 { email = abcd@example.com}",
		           "Delete": false

			}]
```

Closing and assuming solved unless I hear otherwise.
