### ISSUE TITLE
.Alert.Vars cann't eval string

### ISSUE THREAD

**Issue by ifooth** [bosun-monitor/bosun#2216]
#### influxdb Data
![image](https://user-images.githubusercontent.com/1853121/35715189-f60b5394-080b-11e8-8e28-9149acc819d7.png)

### bosun alert define
```
$status = last(influx("telegraf", '''select last(status) from healthz group by dc, "name", service ''', "10m", "", "1m"))
$msg = last(influx("telegraf", '''select last(msg) from healthz group by dc, "name", service ''', "10m", "", "1m")) 
```

### the question is
when i use {{.Eval .Alert.Vars.msg }} in template i get 
```
NaN
```
when i use {{.Alert.Vars.msg }} in template i get 
```
last(influx("telegraf", '''select last(msg) from healthz group by dc, "name", service ''', "10m", "", "1m"))
```
but i expect result is the msg string: '-',
**`so, the question is what's the right way to eval the msg value, or just is a bug?`**
_i dig the document cann't find answer, please help._

### Work Environment:
bosun-linux-amd64-0.5.0

**Comment by PeterGrace** [comment]
I'm not familiar with influx, but, is there a method in the query dsl to cast the results?  You're doing select last(msg) and bosun somehow is thinking that is a number.  Does last(msg) in influx normally return a number?  Is it possible that influx is pasting a '-' in your results because there's actually no data there?
