### ISSUE TITLE
scollector missing linux.disk metrics for most NVMe drives

### ISSUE THREAD

**Issue by GenghisJan** [bosun-monitor/bosun#2223]
Hi, folks. In `c_iostat_linux()` in disk_linux.go, it looks like scollector ignores devices with minor device numbers not divisible by 16. This seems to rule out most NVMe devices. E.g., on the following system, I only see metrics for nvme1n1 (using scollector 0.6.0-beta1 or 0.5.0:

```
# ls -l /dev/nvme*
crw------- 1 root root 245, 0 Jan 25 19:01 /dev/nvme0
brw-rw---- 1 root disk 259, 1 Jan 25 19:01 /dev/nvme0n1
brw-rw---- 1 root disk 259, 2 Jan 25 19:01 /dev/nvme0n1p1
brw-rw---- 1 root disk 259, 3 Jan 25 19:01 /dev/nvme0n1p2
crw------- 1 root root 245, 1 Jan 25 19:01 /dev/nvme1
brw-rw---- 1 root disk 259, 0 Jan 25 19:01 /dev/nvme1n1
crw------- 1 root root 245, 2 Jan 25 19:01 /dev/nvme2
brw-rw---- 1 root disk 259, 4 Jan 25 19:01 /dev/nvme2n1
crw------- 1 root root 245, 3 Jan 25 19:01 /dev/nvme3
brw-rw---- 1 root disk 259, 5 Jan 25 19:01 /dev/nvme3n1
```

```
# cat /proc/diskstats
 259       0 nvme1n1 320108 0 81924672 17033 0 0 0 0 0 14709 17020
 259       1 nvme0n1 1629459 13 409192557 81767 262709 28111 5097652 195786 0 205694 277471
 259       2 nvme0n1p1 10401 0 2209439 526 164 5 99997 254 0 559 780
 259       3 nvme0n1p2 1618974 13 406978694 81233 216496 28106 4997655 163689 0 180896 244794
 259       4 nvme2n1 320111 0 81924672 17698 0 0 0 0 0 17517 17671
 259       5 nvme3n1 320111 0 81924672 17472 0 0 0 0 0 17273 17434
   8      32 sdc 473 0 7336 43 0 0 0 0 0 41 43
   8      48 sdd 473 0 7336 49 0 0 0 0 0 43 48
   8      64 sde 473 0 7336 50 0 0 0 0 0 47 49
   8       0 sda 473 0 7336 80 0 0 0 0 0 68 80
   8      16 sdb 473 0 7336 48 0 0 0 0 0 47 48
   8      80 sdf 473 0 7336 50 0 0 0 0 0 49 50
 253       0 dm-0 32970 0 1002708 2924 247790 0 4993559 203535 0 133713 208120
 253       1 dm-1 141 0 6560 7 0 0 0 0 0 4 7
 253       2 dm-2 88 0 2178 5 4 0 4096 1 0 6 6
```

Any thoughts on how scollector might catch more of the NVMe's without breaking other stuff? Horrible special-case?

Thanks,
Jan

**Comment by capnsue** [comment]
Hey, just jumping in here to say that I'm experiencing this with scollector 0.8.0-Preview --  does anyone have a patch or a workaround?  (i'm running centos 7 if that matters)

**Comment by alaincao** [comment]
Heylow,
if anyone is still interested in this, I have a ~fix~ *big fat ugly hack* that seem to work ***for me*** available at  
https://github.com/alaincao/bosun/commit/88d80bbbf21eab005dd821905f0d4e9491a6c253  

nb: if you ever want to compile using my branch (may god have mercy on you), be aware that:  
- it is branching a very old version (at 0.8.0-dev apparently) because whatever is in master right now does not work at all for me (and I need something working quickly until I find a replacement monitoring system ...)
- it contains ~patches~ *ugly hacks* for *other* issues with Debian Bullseye & Ubuntu 20.04 (cf. last 5 commits).
- if you have Docker installed, just do `$ docker-compose up` and the executable should appear in `./cmd/scollector/`.
