### ISSUE TITLE
Release new version > 0.8.0

### ISSUE THREAD

**Issue by gdubicki** [bosun-monitor/bosun#2230]
Hi,

We have been using Bosun extensively and are very happy with what it provides. Thank you for this great tool!

But we would have more confidence in it's future if you would release new version.

So is it coming?

Thanks,
Greg

**Comment by gdubicki** [comment]
<chirp chirp>

**Comment by gdubicki** [comment]
Who should we ping about the release, @muffix ? I see that you are not working for Skyscanner anymore. Do you know who took over this project?

**Comment by muffix** [comment]
The project is still being maintained by the same people, but there's still more work to do before we're planning a new release. No need to ping anybody at this time.

**Comment by gdubicki** [comment]
Cool, thanks for a quick and relieving response, @muffix ! I was afraid that the project got unmaintained again.. :) May I keep this issue open so other people asking for the release can upvote it instead of creating new issues?

**Comment by johnewing1** [comment]
Hey, please keep open.  We kicked off the stale bot because we had an overwhelming number of historic issues and PRs.  Responses like this help us plan where to put our time. Thanks

**Comment by breml** [comment]
It is now close to a year since the last update on this issue and I am wondering about the maintenance state of this project.

We are currently evaluating a monitoring/alerting/notification solution for metrics stored in Elasticsearch. Bosun ticks a lot of the boxes in our wish list, but we are a bit nervous about the future of this project. The official web page still states, that Skyscanner has taken ownership of this project and will continue to maintain it. Is this still true? Based on the Github profile of @muffix , he is no longer with Skyscanner. Who are the people at Skyscanner, who maintain Bosun? Is there still work being done towards a next official release? We needed to compile current master of Bosun our selves in order to get it running with Elasticsearch 7.x. The last release of Bosun dates from 10th October 2018 and was still done by @kylebrandt so it looks to me, that Skyscanner did not release any new version since then.

I would be glad to hear from any side, if it is still worth investing in Bosun.

**Comment by breml** [comment]
Maybe @johnewing1  or @neilfordyce can chime in on this issue.
