### ISSUE TITLE
Inconsistent behaviour with over() compared to bandTSDB() and window()

### ISSUE THREAD

**Issue by DCBoland** [bosun-monitor/bosun#2297]
Using `over()` results in a seriesSet containing a series starting now, i.e. `{shift=0s}`. This is unexpected and inconsistent with the behaviour of `bandTSDB()` and `window()`, which start `period` ago. This is an issue when trying to calculate a historical distribution, median etc. using the new `aggr()` function, as the current value will be included.

The above inconsistency appears to be because `over()` subtracts `period` from now at the end of its loop, whereas the other functions do the subtraction at the start of their loops:
https://github.com/bosun-monitor/bosun/blob/4bec6475bb8f41f0f683910b90c11c8ab4a633e3/cmd/bosun/expr/tsdb.go#L386

Potential solutions:
- Change `over()`'s behaviour to be in line with the other functions
- Add parameters to set a start time or offset.

I'm assuming the first option would cause too many problems to be acceptable?

Context:
[aggr() function PR](https://github.com/bosun-monitor/bosun/pull/2294)

**Comment by kylebrandt** [comment]
`over()` was created for making week over week graphs, for which you want the current week. So I don't think we should change the behavior.

So instead I think we should just add another function that behaves like band and window, I'm not sure what to call it.

**Comment by hermanschaaf** [comment]
If we do create another function, can we add another parameter for explicitly specifying the end time, rather than using `period` for this? This would allow us to more easily account for minor metric delays, and also achieve what @DCBoland described. Though we may need one like this for `band` and another for `over` (with time shifting included)

**Comment by DCBoland** [comment]
While looking at the above, I spotted the undocumented `shiftBand` function, which appears to return an `over`-like seriesSet, with the `period` shift behaviour from `band` – exactly what I needed!

The above commit is along the lines of @hermanschaaf's suggestion. Adds an `eduration` parameter to generic versions of `band` and `over`, named `bandQuery` and `overQuery`, to set the end time as is done with `Query`.  The original functions just wrap these new ones, with `period` given as the `eduration` to match the existing behaviour.

**Comment by kylebrandt** [comment]
@DCBoland Nice I like it, adds what people want without messing with current behavior (or at least it shouldn't). 

Needs expr documentation in docs.md (can you add for the shiftBand ... easter egg :p ... as well?)

Then if you add some tests it will be easier for me to look over the code and merge it since I don't have test things locally as much.
