### ISSUE TITLE
Support tagging of alert instantiations

### ISSUE THREAD

**Issue by kylebrandt** [bosun-monitor/bosun#324]
During human actions. We should support either predefined or user defined tags. The problem is that we have no data on how many alerts are false or redundant. By allowing users to tag this sort of thing when ack or maybevand/or close we could analyze how we are doing with the signal to nose radio of alerts. We could also maybe find problematic alerts.

This feature needs more definition. (Which should probably be a github issue label)

**Comment by Dieterbe** [comment]
after using bosun for a little longer, and making use of the timeline to iteratively develop my alerts, i realized what would be very useful to me is this:
* a way to have markers (problem-start, problem-stop, associated to rules) over time in some kind of database, to mark faulty timeframes, i.e. time frames during which the alert should trigger. we could visually use this to match against the green/red timeline.  right now, i'm always struggling with getting value out of the timeline, because i can't remember when all the issues happened. i can easily tweak the alert to match recent (the last) events, because i know them, but i might negatively impact performance of the rule without even knowing.
we could even compute a rule "score", by calculating how well the back-in-time statuses line up with these marked timeframes.
* so we can get great value out of precisely marked time ranges.  this goes a bit beyond just hitting a link in an alert "yes this alert was good", or "no this alert was no good".  I think this is a good start, and allows the person who got the alert to create some initial markers, but then i think we still should have an interface to finetune the markers and adjust timeranges visually, typically by showing one or more of the timeseries that serve as input to the rule, so you can spot issues visually and adjust the markers accordingly.

related work:
* #657 where i'm working on displaying timeseries along with the red/green status timeline in bosun 
* https://github.com/Dieterbe/anthracite/ a database for "all changes and events that can have a business and/or operational impact.", it has tagged events and supports a few special events like outage start/detected/resolved markers from which it computes operational metrics like MTTD/MTTR
might make sense to work with its database (ES) to store said markers, because various graphite dashboards can display those events as annotations to graphs.  though i don't feel strongly about this. it might be simpler to store the markers in bosun's database, but i'ld like to have them available in my charts so then we'd have to update our dashboards to support querying the bosun db.

**Comment by kylebrandt** [comment]
I'm also longing for annotations. i.e. people can globally annotate stuff
they have done that might impact stuff. Which often I might not want tied
to an alert. These could also connect to silences.

I'm not entirely sure if this is a few features or one bigger feature. I
think we need to cleanup bosun's "database" before taking this on though :-/

On Fri, Feb 13, 2015 at 12:12 PM, Dieter Plaetinck <notifications@github.com

**Comment by kylebrandt** [comment]
Another useful addition would be to have our band functions be aware of
some of these windows. We could mark periods of time to be ignored by band
for certain alerts.

Basically say "exclude this" when band fetches history. That way when
abnormal stuff happens that abnormal event won't be used to construct
history.

**Comment by Dieterbe** [comment]
also, timeframes that are not explicitly marked as positive (positive meaning there was an issue which should trigger an alert), are assumed to be negative right? or not? either way, it makes sense to support explicitly marking timeframes explicitly as negative so that you can convey things like "i know that the timeseries behaves funky here but there wasn't really an issue here i swear, it only looks like it because a b c but actually it was merely d e f",  because whenever you work on alerts and want to make sure that your historical positive/negative declarations are in good shape (a must before tuning the alert!) you might notice weird issues in the input series and wonder whether there was a true issue there (that hasn't been annotated yet) or not, and an explicit negative fixes this.

thinking a bit further, i wonder whether we need some sort of time-bound version control, so that history is preserved as you modify annotated timeframes to be positive then negative then back positive for example, which can happen as new information comes to light, as you update info, you want to be aware of older annotations that cover a timeframe that overlap with the one of the current context.  this might be overkill, but maybe not.

**Comment by Dieterbe** [comment]
i started working on this. see https://github.com/grafana/grafana/pull/1569
my vision is to leverage grafana to edit/create known good/bad timeranges, we can execute the historical test in bosun, compute the scoring, and visualize everything in grafana
