### ISSUE TITLE
Red/Yellow/Green should be avoided unless indicating Error/Warn/Good Status

### ISSUE THREAD

**Issue by GABeech** [bosun-monitor/bosun#331]
In a few places - most notably the graphs. Red is used as one of the first colors to differentiate different things. 

In the context of monitoring
 Red == Problem
Yellow == Something wrong
Green == All good

It is very confusing and panic inducing to see a whole bunch of red all over a host graph.

**Comment by captncraig** [comment]
Colorblind checking in. I often have problems distinguishing green/yellow, although I do not have this problem with bosun. At least on the dashboard the yellow/green are distinct enough to not cause problems. 

The problem with graphs is that you need each line to be distinct from the others. To do so without using red seems a bit unnecessary to me. 

Is there any point where we add good/bad status annotations on a graph? If so we should not be drawing attention away from them with line colors. Otherwise, my opinion is that graph colors should not matter, so long that colors have relatively constant contrast from the background (so no color stands out naturally).

As we are already shifting the emphasis away fro bosun and toward grafana for visualizations, perhaps  we should do nothing here.

**Comment by kylebrandt** [comment]
Due to the finite amount of colors it isn't really practical to get rid of them. I did however change it so that red is last on the list of color options for both the UI and the graphs embedded in the notification.
