### ISSUE TITLE
Ability to remove hosts in UI or REST API

### ISSUE THREAD

**Issue by ryan1234** [bosun-monitor/bosun#611]
I looked through outstanding issues and didn't see this request, so hopefully it's not a duplicate.

Situation: I have a Bosun machine running and I'm going one by one and putting scollector on machines in our infrastructure. Many of the machines get rebooted/reimaged (Azure) and so the hostname can change. 

The issue is that I end up with orphaned hostnames in Bosun and I end up restarting the Docker container to flush them out.

It would be awesome to have the ability to delete a host from the UI to clean up orphaned machines. Or I suppose an API endpoint could do this as well? 

I realize this is more for machines that are in the cloud and not applicable for other environments.

**Comment by ryan1234** [comment]
That helps. Still learning the in's and out's of the tool. It's not the end of the world for us right now to restart the docker container. Once we get more integrated with production machines it will become a little more annoying, but we can live with it for now.

**Comment by kylebrandt** [comment]
Items page now only shows items of a certain age, so considering this fixed.

**Comment by talonx** [comment]
I know this issue is closed but posting here without reopening the issue since I had a related question. Forgetting seems to apply to alerts only, not hosts, right? How do I forget a host without having unknown alerts generated at all? In a cloud environment, hosts go up and down all the time, e.g. due to autoscaling. It's pretty easy to hook into these events and call Bosun's API, but only if I can forget all the time series(es) for a given host, and without waiting for any unknown alerts generated. Is there a way to do this in the Bosun API?
