### ISSUE TITLE
unclear "expr: unexpected // in func" error on Rule page.

### ISSUE THREAD

**Issue by Dieterbe** [bosun-monitor/bosun#662]
error:
```
conf: Test Config:51:4: at <warn = max($bad_all)...>: expr: unexpected // in func
```

alerting config:
```
alert requests_by_country {
    template = generic
    $rbc = "groupByNode(stats.web*.request_by_country.*,1,'sum')"
    $duration = "10m" // probably should be per-country with lookup table
    $period = "7d"
    $lookback = 4
    $rbc_hist = graphiteBand($rbc, $duration, $period, "country",$lookback)
    $rbc_now = graphite($rbc, $duration, "country")
    $rbc_hist_med = median($rbc_hist)
    $rbc_hist_dev= dev($rbc_hist)
    $rbc_now_med = median($rbc_now)
    $bad = ($rbc_hist_med - $rbc_now_med) > $rbc_hist_dev*4
    $bad_all = t($bad, "")
    warn = max($bad_all) > 0
}
```

**Comment by Dieterbe** [comment]
turns out it's due to the // on line 4. but the point remains: this error is unclear and from the looks like it, in correct (what does Config:51:4 mean? line 51 col 4 ?) also why does it reference `max($bad_all)`

**Comment by mjibson** [comment]
Yes, this error message could be improved. Config:51:4 means line 51, col 4 of the file "Config". This is more useful when it reports the line number from your production bosun config file, not so useful from the web interface where it appends a bunch of stuff and so the line numbers don't match up with the web interface.

The error about max is due to how variables are handled. They are just dumb text replacement, so the expression parser doesn't know the line they came from. A hard problem to solve.

**Comment by kylebrandt** [comment]
Replacing with new issue
