### ISSUE TITLE
os and linux what is the difference?

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#702]
example:
os.mem vs linux.mem
os.net vs linux.net
os.disk vs linux.disk

**Comment by kylebrandt** [comment]
Often they will be the same. os.* exists so we can have a unified view of
things that we can transform to standard across operating systems. For
example os.cpu is utilization 0-100% as a counter for both Linux and
Windows.

Since OpenTSDB is very storage efficient I don't worry about the
duplication of data.

This way only one alert needs to be written for host cpu (instead of one
per OS) in a mixed environment (like we have at Stack).

**Comment by wkshare** [comment]
i got it
