### ISSUE TITLE
Bosun: Ability to auto close alerts when they go from warn/crit to normal

### ISSUE THREAD

**Issue by gbrayut** [bosun-monitor/bosun#792]
For our exceptional alerts we would like them to auto close when they go from warn/crit to normal. That combined with an escalation chain should mean they will fire any time they evaluate to warn/crit (unless someone acknowledges them). I think an acknowledged alert should still close when it goes normal, but leave that up to Matt/Kyle.

**Comment by kylebrandt** [comment]
The use case makes sense to me now. Basically it is conditional logging
(log every check interval if condition) and the log entry happens to be a
bosun notification. There are instances where makes sense to have bosun do
this since it already has the data and the expressions required.

We should also think about if these should be on the dashboard since they
are not part of the dashboards intended alert workflow.

Reporting is similar nature, except the condition is time (a schedule)
perhaps paired with an expression condition. I.e. If $q at $thistime then
notify.

Since both these feature behave similarly, perhaps we should support it
more directly than the implementation we chatted about and Greg wrote down.

**Comment by mjibson** [comment]
A new section called `log`? Or a `log = true` setting in `alert`?

**Comment by gbrayut** [comment]
This has been implemented
