### ISSUE TITLE
Does the config file support "includes"

### ISSUE THREAD

**Issue by gpocina** [bosun-monitor/bosun#942]
Is the config file monolithic, or is there some way to put alerts, templates, etc., into seperate files, and include them from the config file, in order to aid configuration management?

**Comment by mjibson** [comment]
Currently it's one big file. No includes. We've discussed doing something like this before but not arrived on anything.

**Comment by mxk1235** [comment]
this feature would be great.  can you give us an update on what the current thinking around it is?

thanks in advance!

**Comment by gpocina** [comment]
I defer to the bosun developers for what they had in mind when they
discussed it.

As far as my own use goes, our configuration management package, bcfg2, has
the idea of bundles specific to chunks of infrastructure.  For example a
"named.XML" bundle might specify relevant named rpm packages, configuration
and zone files, and tcollector tsdb collector scripts needed for a DNS
server.

My thinking was that it would be nice if I could also automatically specify
bosun configs specific to named servers in the bundle.  The goal being when
you designate a node as running named, it automatically gets all the sw,
configs, monitoring, and alerts, without any extra steps being needed.

However after some thought I realized that there was a flaw in this in that
bcfg2 bundles specify that files that go to a target node.  This works
great for collectors,  but bosun rules don't normally go to the host being
monitored.

While not a match for bcfg2 bundles, bosun includes might still provide
some more options in how a potentially large config is managed,  but I'm
far from a bosun expert.

**Comment by mxk1235** [comment]
that is roughly the use-case we want to cover.  we are likely to have sets of alerts per host, but also per service.  potentially, this is hundreds if not thousands of rules.

**Comment by kylebrandt** [comment]
Nothing against the idea of includes, but because order matters in the config currently, that would need to be taken into consideration. Probably the biggest challenge would be the Rule Editor UI changes. This currently isn't a priority at Stack.

I am concerned about some of the underlying ideas of thousands of rules. The idea is that one alert definition applies to many hosts, services, etc. So when you add a new service or host, scollector automatically detects it, starts sending data, and then the alert apply to that new data by default. If you need to change certain cases, lookup tables are used. 

I'd be interested in seeing some sections of your config, I have a feeling that you maybe writing alerting rules in a suboptimal way.

**Comment by gpocina** [comment]
Thanks, I agree.   I haven't written many bosun rules yet, but it had
become clear the trying to manage bosun rules that are based on tsdb
metrics (that already have hostname abstracted out of them via a "host="
tag), using a host specific features of the configuration manager, wasn't
going to work.

That said, it would be nice to be able to do something that allows multiple
people to simultaneously develop bosun rules, using something like version
control.   Git + a single large config file would work, but git + and
handful of smaller include files might be better.

I see a ticket related to config management workflow, including to
possibility of using git:
https://github.com/bosun-monitor/bosun/issues/420

It looks like the matter is still under consideration.   That issue is
probably the best place to continue this topic.

Thanks.

**Comment by mxk1235** [comment]
We don't have a config file yet.  I am just playing around with bosun right now trying to see if i can get feature parity with our current system, which is simply separate [check_tsd] (https://github.com/OpenTSDB/opentsdb/blob/master/tools/check_tsd) calls done via something like [sensu-client] (https://sensuapp.org/docs/latest/clients) or a [nagios plugin] (https://github.com/NagiosEnterprises/nrpe).

off the top of my head, there's probably a dozen different metrics per service to monitor, which change depending on service (total qps, qps per endpoint, p50/75/95 per endpoint and per host, total error codes and per host, cache misses, payload size for POST endpoints).

it looks like some of these can be grouped if they are represented in opentsdb by the same metric and differ by different tag values for service name, endpoint name, and host name.  however, if they are separate metrics, that may not be convenient, and some services have many endpoints that need monitoring while others only have one (or none).

even if one alert can be created for a set of services, i may need to set different critical levels for the same metric.  it appears that i would have to mention all the values in the same alert definition, which makes the config harder to maintain.  taking an example from your docs.  the lookup section would have to include every value for every service.  i'd rather keep those separated by service, rather than grouped by alert.

```
lookup l {
	entry service=a {
		v = n
	entry service=b* {
		v = d
	}
}

alert a {
	crit = 1
	critNotification = all # All alerts have the all notification.
	# Other alerts are passed through the l lookup table and may add n or d.
	# If the host tag does not match a or b*, no other notification is added.
	critNotification = lookup("l", "v")
	# Do not evaluate this alert if its host is down.
	depends = alert("host.down", "crit")
}
```

something to consider.

**Comment by tdinucci** [comment]
This is something we (Skyscanner) had implemented internally and we will soon be merging our internal changes into this project.

Closing this particular ticket as it is very old and this is currently on our radar.
