### ISSUE TITLE
We want to hide SMTP information

### ISSUE THREAD

**Issue by wkshare** [bosun-monitor/bosun#950]
smtpUsername: SMTP username
smtpPassword: SMTP password

With all the information, but the configuration page, I don't want to show up

**Comment by kylebrandt** [comment]
Environment variables are made available to the config, for example:

`shortURLKey = ${env.GOOGL_API_KEY}`

This isn't that secure because access to the machine will reveal the keys, but it does make it so the config page via the web UI or API doesn't show the secrets.

Reopen if you still have an issue.

**Comment by wkshare** [comment]
Thks, @kylebrandt

**Comment by mjibson** [comment]
Please note that this is trivial to work around and does not provide security, just obscurity. For example, you can still do this in you rule editor to get around it:

```
template t {
    subject = {{V "${env.YOUR_VAR}"}}
}

alert a {
    crit = 1
    template = t
}
```

We do not currently have a real solution to this problem.

**Comment by gbrayut** [comment]
Correct. In this case I equate it to using *** instead of the real characters when typing your password. Even if you could still copy/paste out of the text box or capture using keylogger at least you cannot accidentally expose the secrets to someone looking over your shoulder. Things like AWS keys or high security accounts should still not be put in these config files.

I mentioned to Jason that integration with [blackbox](https://github.com/StackExchange/blackbox) and a special ${blackbox.variablename} format that is only valid in certain places (like no templates) would be a good long term solution, but right now we don't have a use case that justifies the effort.
